rules:
  class-methods-use-this: 0
  no-useless-constructor: 0
  no-empty-function: 0
  import/prefer-default-export: 0
  '@typescript-eslint/no-unused-vars': ['error', { 'ignoreRestSiblings': true }]
  indent: 0
  # max line length 80, except for "strings" and `template literals`
  max-len:
    - 0
    - ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreComments: true
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/explicit-module-boundary-types': 0
  no-case-declarations: 0
  quotes: 0
  no-console: 0